### ISSUE TITLE
Add QoS-Final-Unit-Indication AVP

### ISSUE THREAD

**Issue by lbertz02** [lbertz02/rfc4006bis#3]

**Comment by lbertz02** [comment]
draft-bertz-dime-rfc4006bis-filterrule.xml closes this issue but kept in a separate file due to the number of changes.  Will incorporate into main document when we get mailing list consensus

**Comment by dcdolson** [comment]
I thought you might make a branch in git.

From: Lyle Bertz
Sent: Wednesday, June 29, 2016 10:40 AM
To: lbertz02/rfc4006bis
Reply To: lbertz02/rfc4006bis
Subject: Re: [lbertz02/rfc4006bis] Upgrade Restriction-Filter-Rule AVP to also support RFC 5777 (#3)

draft-bertz-dime-rfc4006bis-filterrule.xml closes this issue but kept in a separate file due to the number of changes. Will incorporate into main document when we get mailing list consensus

�

**Comment by lbertz02** [comment]
QoS-Final-Unit-Indication (Q-F-U-I)
- Current Final-Unit-Indication 
  - uses Filter-Id or Restriction-Filter-Rule (type is IPFilterRule)
  - Implication: Any rule that is QoS based MUST have a Filter-Id to be used in F-U-I and installed separately
  - No direct support for QoS in the restriction Filters
- Proposal: Q-F-U-I  (new AVP) that 
  - replaces Restriction-Filter-Rule with Filter-Rule (RFC 5777)
  - is extensible
- Notes added in 
  - F-U-I AVP Section that if you want QoS in a Rule it MUST be addressable as Filter-Id or use Q-F-U-I
  - Q-F-U-I AVP that if you require backwards compatibility you MUST use F-U-I
